### ISSUE TITLE
Crash with missing valhalla.json

### ISSUE THREAD

**Issue by RomanJuranek** [gis-ops/docker-valhalla#105]
The instructions in README do not include creating valhalla.json. When the file is missing, starting docker image fails on runtime error.

```
============================
= Build the initial graph. =
============================
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not parse json, error at offset: 0
/valhalla/scripts/configure_valhalla.sh: line 210:    56 Aborted                 (core dumped) valhalla_build_tiles -c ${CONFIG_FILE} -e build ${files}
```
It seems that empty json is created along the way but it cannot be parsed. Adding empty object in the json solves the problem.
`valhalla.json`:
```json
{}
```

**Comment by chrstnbwnkl** [comment]
This should be fixed with #104 .

**Comment by nilsnolde** [comment]
You sure? This sounds like a very different problem no?

**Comment by nilsnolde** [comment]
Ah right, you're saying that `valhalla_build_config` errored  out because of #103  (and OP isn't showing those logs) and now it's throwing because that file is empty? Makes sense :smile:

**Comment by chrstnbwnkl** [comment]
Yeah, the fact that `valhalla_build_config` just created an empty `valhalla.json` threw me off as well at first :D
