### ISSUE TITLE
New feature: write logfile to a custom mounted volume

### ISSUE THREAD

**Issue by gschimon** [gis-ops/docker-valhalla#11]
Would be nice to have the possibility to write a logfile to a volume that is accessible from the host system.
Can be in "custom_files" or maybe even better in an extra volume mount (e.g. "log_files")

Could be implemented with rsyslog inside the container.

**Comment by nilsnolde** [comment]
I think you better deal with this on the host, not inside the container, e.g.:
https://docs.docker.com/config/containers/logging/configure/

**Comment by nilsnolde** [comment]
someone also came up with a rsyslog solution:
https://www.simulmedia.com/blog/2016/02/19/centralized-docker-logging-with-rsyslog/

**Comment by gschimon** [comment]
You are right. That is probably the better solution.
Thanks!
