### ISSUE TITLE
Problem setting permissions to docker image

### ISSUE THREAD

**Issue by frenando** [gis-ops/docker-valhalla#112]
Hello,

I think the documentation for the UID and GID is incomplete and also not working, at least in Fedora, i'm Trying ti use the default docker-compose.yml from the template and files cannot be created and despite the fact i'm explicitly setting the UID and GID as 1000:1000 so that it uses the same permissions my user has, however,  its not working

![Screenshot from 2023-06-17 22-42-32](https://github.com/gis-ops/docker-valhalla/assets/9635605/9414a5ac-aa5b-49a5-bd84-3b32996dd23e)
![Screenshot from 2023-06-17 22-43-13](https://github.com/gis-ops/docker-valhalla/assets/9635605/862aaaa0-fea6-4f0f-b028-25fe15f544f5)

**Comment by nilsnolde** [comment]
TBH, I was never really happy with this.. I hacked that in for a client use case that was fairly complicated with permission stuff. And it worked (and still works), but it could probably be removed to use explicit UID/GID when running a container. But I might miss smth there.. 

It is tested in CI, but again, I’m not 100% on it really working for all scenarios. Other than that one client case I’m never using custom UIDs.

**Comment by frenando** [comment]
Thanks a lot for your reponse, in the end i found out it was actually SELinux blocking docker
