### ISSUE TITLE
Valhalla.json documentation

### ISSUE THREAD

**Issue by blue-bear-tech** [gis-ops/docker-valhalla#117]
Hello,

I can't find anywhere the documentation for the config file.
I'm running Europe on a 7 threads 14 GB of RAM ubuntu server, in htop I see that it's using 1.4 GB of ram at max with 100% CPU when running some performance tests.
Can I give Valhalla more RAM and see if it has better performance?

Edit:
I just found scripts/valhalla_build_config file.

**Comment by nilsnolde** [comment]
Properly running Valhalla is a big topic tbh. Just use the .tar file (default) and Valhalla will be in mmap mode.

Ideally you give it as much RAM as the tar file weighs (so around 30 GB approx), so the graph can be (kinda) cached properly. And then some for the algorithms to do their work. And no other process running on that server. 

Anyways, if you're doing load testing and you still have some free memory, then upping that won't improve performance. Using fast processors & fast disks will. If you do serious stuff, then you might wanna deep dive in Valhalla's architecture.
