### ISSUE TITLE
Safely re-generate valhalla.json to update new keys in new versions

### ISSUE THREAD

**Issue by danceb** [gis-ops/docker-valhalla#118]
We had the issue that the memory was not cleared after matrix calculations and after another ram consuming calculation the application died. I came around https://github.com/valhalla/valhalla/pull/4075, where this issue is treated, as it seems. 

Within https://github.com/valhalla/valhalla/pull/4075/commits/76b33d882cc3e6421a07d72d4e1e2f793c5ba080#diff-b3846614879a01a4589cc7be405a97326b3c79e8a9e64944d4f94a41c5d478e6 the parameters `max_reserved_labels_count_matrix` and `clear_reserved_memory_matrix` are introduced, but I am missing these within `custom_files/valhalla.json` which comes with the current 3.4.0 image.

I think these (and maybe others, I don't know) are missing within the building of the `custom_files/valhalla.json` file? So it would be nice, if this could contain the current state of all parameters, which can be used to configure valhalla's behavior. Thanks!

**Comment by nilsnolde** [comment]
We don't distribute the config file, that's left from your previous installation, and so far it's the operator's responsibility to keep this up-to-date. I understand that's a gotcha and one has to be careful when re-generating the config by deleting and re-starting the service. I'd be open for a PR that 
- checks if there's an existing config file (we have that logic already)
- if so, generates a new temp config file
- checks if the existing config is missing any key compared to the new one
- copies in any missing keys with default options

The important part is to not overwrite anything that's been previously set in the existing config.
