### ISSUE TITLE
Latest docker image is broken

### ISSUE THREAD

**Issue by azhi** [gis-ops/docker-valhalla#12]
It fails with:

```
/valhalla/scripts/run.sh: line 12: valhalla_service: command not found
```

Looks like it was broken by https://github.com/gis-ops/docker-valhalla/commit/557dc6d184410ced685c3e3be769d0885967fcd8#diff-7e6be3d854e9fb8ceb89fe48fc1bb68083ca2a4bf4db5b80b5743ebe2eb88960R22 - `valhalla_service` executable is part of ENABLE_TOOLS, so I guess ENABLE_TOOLS should be ON :)

**Comment by nilsnolde** [comment]
Oh damn.. you're right! just didn't want to build those useless other tools :sweat_smile: . Give it an hourish and it'll be ok again! Need to integrate some testing here..

**Comment by nilsnolde** [comment]
ok, building already, should be online soon
