### ISSUE TITLE
Can't pull docker image

### ISSUE THREAD

**Issue by khamaileon** [gis-ops/docker-valhalla#122]
docker pull ghcr.io/gis-ops/docker-valhalla/valhalla:3.4.0

gives me:

Error response from daemon: Head "https://ghcr.io/v2/gis-ops/docker-valhalla/valhalla/manifests/3.4.0": denied: denied

**Comment by ImreSamu** [comment]
> Error response from daemon ...

It’s possible that the access token you used to log in has expired or is invalid.
* https://everythingtech.dev/2022/09/how-to-fix-docker-unauthorized-from-pulling-from-github-private-packages-ghcr-io/
* https://github.com/orgs/community/discussions/43380#discussioncomment-4601450

**Comment by khamaileon** [comment]
It's a bummer to have to be logged in. Isn't there a way to make the repository public like on Dockerhub?

**Comment by ImreSamu** [comment]
it is public.

```
root@vmi9999999:~# docker logout ghcr.io
Removing login credentials for ghcr.io

root@vmi9999999:~# docker pull ghcr.io/gis-ops/docker-valhalla/valhalla:3.4.0
3.4.0: Pulling from gis-ops/docker-valhalla/valhalla
3f94e4e483ea: Pull complete 
7a4381819873: Pull complete 
fccefcba7079: Pull complete 
cf013d9fa0af: Pull complete 
61f67836920e: Pull complete 
e40dae05dbfc: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:e51408745e49ea888ce4a9ab7408636a238d8ae2d463a9ee29ac7351d06f4132
Status: Downloaded newer image for ghcr.io/gis-ops/docker-valhalla/valhalla:3.4.0
ghcr.io/gis-ops/docker-valhalla/valhalla:3.4.0

```

**Comment by ImreSamu** [comment]
try to `docker logout ghcr.io`

https://stackoverflow.com/questions/74795993/unable-to-pull-public-image-from-github-container-registry-ghcr
