### ISSUE TITLE
Latest build broken because of cmake / protobuf changes?

### ISSUE THREAD

**Issue by Temetz** [gis-ops/docker-valhalla#123]
The latest tagged docker image is broken, most likely because of changes made to valhalla build process.

Running the latest docker image errors out with the following error:
```
error while loading shared libraries: libprotobuf-lite.so.32: cannot open shared object file: No such file or directory
```

Potentially caused by: https://github.com/valhalla/valhalla/pull/4334
Or: https://github.com/valhalla/valhalla/pull/4213

As workaound one can use the image tagged as 3.4.0

**Comment by nilsnolde** [comment]
Must be a glitch, that's pretty much impossible in a proper build. If this is really the problem, it's either a bug with the debian protobuf, ld or some other build toolchain, which is all very unlikely. Here someone tried the latest image and it seems to work: https://github.com/valhalla/valhalla/issues/4325
