### ISSUE TITLE
Publish arm64 image

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/docker-valhalla#124]
Now that upstream has support for arm64 Docker image, we should publish it here too.

**Comment by BjoernRave** [comment]
WIthout this I can't run this container on an apple silicon mac right?

**Comment by nilsnolde** [comment]
Right.

**Comment by BjoernRave** [comment]
can I be of any help? If you give me some pointers at how to do it, I might be able to. Would love to use valhalla on my apple silicon mac

**Comment by nilsnolde** [comment]
it needs some adjustment in the dockerfile to adapt to the new dockerfile upstream (e.g. the base image changed to 23.04) and a few other changes, plus of course the github action to build and publish the arm64 image. it's quite mechanical. if no one else jumps at it, I'll get to it at some point. since it's of so little interest to ourselves, it might take a bit longer. happy to review PRs though.

**Comment by nilsnolde** [comment]
and fwiw, people can already use the native valhalla image. it's just a bit more manual in how you'd run it.
