### ISSUE TITLE
Road transit times using default configuration

### ISSUE THREAD

**Issue by johndporter** [gis-ops/docker-valhalla#135]
I am using the default docker image and a tile set for the uk. The transit times for routes are very different from those of tomtom and google with transit times 50% shorter when using my valhalla docker container (eg 346 vs 530secs) . Routing generally seems to be correct and all distances are very similar. This is on routes which do not have any traffic delays, but do have speed limits.

Using the valhalla server at https://valhalla1.openstreetmap.de/route returns similar results to tomtom and google. Is it using a different configuration for road speeds? I can't find any way of looking at the configuration for that server.

**Comment by nilsnolde** [comment]
Jep it does, you can try with this: https://github.com/OpenStreetMapSpeeds/schema/blob/master/default_speeds.json. Download the json and set the path in `mjolnir.default_speeds_config`. That could be automated, happy to review a PR to do just that.

**Comment by johndporter** [comment]
Simply adding the mjolnir.default_speeds_config setting to valhalla.json actually works.

The problem was that something wasn't getting rebuilt with force_rebuild=True in the build config. Explicitly deleting the valhalla_tiles/ and valhalla_tiles.tar from the custom_files directory and then rebuilding fixes the problem.

build_admins=True doesn't seem necessary.

**Comment by nilsnolde** [comment]
If you didn't build the admins sqlite, it can't work. It's needed to map the right ISO codes from the edges to the speeds JSON. Anyways, happy it seemed to have (somehow) worked for you. In the meantime @chrstnbwnkl has raised a PR to deal with automatically:) https://github.com/gis-ops/docker-valhalla/pull/136

**Comment by chrstnbwnkl** [comment]
This is expected behavior. If you want to force a new graph build, you can pass `force_rebuild=True` instead of deleting the tiles yourself. The default is `False`, so it will just fall back to the existing tiles

**Comment by nilsnolde** [comment]
That might very well be. I think there's a slight bug where that forcing will rebuild the tile dir but not remove the tar, so currently you'll have to force the "build_tar" as wel

**Comment by johndporter** [comment]
Is there another issue, that triggering the rebuild of the tiles (because something changes like the config file or presumably the pbf file) and this does not cause the tar file to rebuild. This seems to have been happening as well.
