### ISSUE TITLE
Bus error (valhalla_build_tiles)

### ISSUE THREAD

**Issue by akifaktas** [gis-ops/docker-valhalla#142]
Hi! When I tried to install Valhalla with Docker on a virtualized server, while everything was going well, I received the following error after hours:

/valhalla/scripts/configure_valhalla.sh: line 228:    62 Bus error               (core dumped) valhalla_build_tiles -c ${CONFIG_FILE} -e build ${files}

When I tried to install smaller countries and continents, there was no problem, but when I tried to install it for Planet or the European continent, I got this error.

How many GB of disk space is required to install Planet?

My Server
128GB Ram - 20 Processors - 780GB SSD - Ubuntu 20.04

If my current system features are sufficient, how can I overcome this problem? If more space is needed I will order new disks for my server.

**Comment by nilsnolde** [comment]
See here: https://github.com/valhalla/valhalla/issues/4548
