### ISSUE TITLE
Please build a fresh docker image for including a recent valhalla fix

### ISSUE THREAD

**Issue by answerquest** [gis-ops/docker-valhalla#143]
Hi, one-time request to maintainers: please build and release a fresh docker image of `ghcr.io/gis-ops/docker-valhalla/valhalla:latest`.

Reason: Routing is broken for many places, example: 
https://www.openstreetmap.org/directions?engine=fossgis_valhalla_car&route=40.878%2C14.273%3B44.185%2C11.116#map=5/43.005/19.468

It is due to this bug : https://github.com/valhalla/valhalla/issues/4600

Which was fixed and merged in main valhalla just yestserday: https://github.com/valhalla/valhalla/pull/4604

The valhalla published docker image  `ghcr.io/valhalla/valhalla:latest` has been updated post this fix: https://github.com/valhalla/valhalla/pkgs/container/valhalla 

But `ghcr.io/gis-ops/docker-valhalla/valhalla:latest` is still 4 days old as of right now: https://github.com/gis-ops/docker-valhalla/pkgs/container/docker-valhalla%2Fvalhalla hence it's carrying the prior buggy valhalla.

**Comment by nilsnolde** [comment]
kicked it off manually
