### ISSUE TITLE
Valhalla docker killed abruptly

### ISSUE THREAD

**Issue by akki401** [gis-ops/docker-valhalla#144]
Hi Team,
The valhalla of europe continent got killed abruptly and when I see the log in the last It says that
{"log":"/valhalla/scripts/run.sh: line 9: 25244 Killed                  sudo -E $1\r\n","stream":"stdout","time":"2024-02-15T16:55:59.415443613Z"}

But there is no clue why it got killed.
Appreciate your help

**Comment by nilsnolde** [comment]
disk size most likely? try the new `latest` in 10 mins or so. you'll still need easily 200 GB or so for temp files.

in either case, it's not an issue with this project but with https://github.com/valhalla/valhalla.
