### ISSUE TITLE
Custom elevation data

### ISSUE THREAD

**Issue by caspg** [gis-ops/docker-valhalla#151]
Thanks for this great Dockerfile!

I would like to use elevation files (hgt files) that I download from other place. What would be best approach to this?

Run the image with `build_elevation` set to false, copy my files into `custom_files/elevation_data` and then run this image again with `force_rebuild` set to true?

I could open PR to add new container recipe.

**Comment by nilsnolde** [comment]
Hm, no idea, never tried that. I'd first copy the files to the relevant directory, then start the graph build with `build_elevation: true`. If those files are truly HGT format and their naming is the exact same as the tilezen tiles, then I guess it should just work.

**Comment by caspg** [comment]
Awesome. I will try it out and will open PR with recipe. I guess it's not very common use case but there are now lot's of open LIDAR data which gives better accuracy. It probably is not that important for costing models, but for example, graphs plotted with results from `/height` will be more accurate.
