### ISSUE TITLE
Adding a Transit Directory

### ISSUE THREAD

**Issue by nicoazel** [gis-ops/docker-valhalla#16]
During `docker-compose up --build`,  after parsing a `.pbf` I notice the line: 
```
[INFO] Transit directory not found. Transit will not be added.
```

Is there an easy way to add a 'Transit directory' with transit data (ideally GTFS) to the `custom_files' directory and have transit data added to, or integrated with, the osm data at container build time?

If not, is there a suggested workflow, or documentation for, integrating both Transit Information and OSM Street Data into the routing graph?

I first looked to the [Valhalla docs](https://github.com/valhalla/valhalla/tree/master/docs) and found [this](https://valhalla.readthedocs.io/en/latest/mjolnir/getting_started_guide/#transit-data) but personally don't know how to follow through on using `--mjolnir-transit-dir` and based on the above [INFO], it seems like something that may already be implemented in your image. 

**P.S.**
*Thank you for making this image! I have wanted to use Valhalla for some time but the source repo has always been too intimidating. This has made Valhalla accessible out of the box and is incredibly useful.*

**Comment by nilsnolde** [comment]
Happy it's helpful:) And yeah, I felt the same way when I first looked at it..

Transit in Valhalla is (very unfortunately) locked in with Transitland currently, which is smth I avoided up to this day. If you can wait a little, there might be help around the corner for native GTFS support: https://github.com/valhalla/valhalla/pull/2835.

**Comment by nilsnolde** [comment]
If you have the patience to go with transitland, you'd build the transit tiles manually (executables inside the container as well) and point valhalla to the parent directory in the `valhalla.json`.
