### ISSUE TITLE
valhalla latest code crashes at build stage for (maybe) large regions

### ISSUE THREAD

**Issue by answerquest** [gis-ops/docker-valhalla#166]
Ref: https://github.com/valhalla/valhalla/issues/4904

Latest ghcr.io/gis-ops/docker-valhalla/valhalla:latest image is crashing out at build stage. I got the same error result for Africa and Europe continent builds.

It's not fully known yet at what point the problem crept into valhalla source code;
but it would be great if someone can find out and then pin this docker image on the last stable commit.

**Comment by chrstnbwnkl** [comment]
Let's see if we can quickly fix this upstream, I doubt it will take very long to hunt this down

**Comment by nikhil-scholarlify** [comment]
one procedural thing that might be important in such cases: 
valhalla original repo has a v3.5.0 release from Aug 21, 
but this repo's docker release doesn't have a corresponding 3.5.0 tag that we could fallback to, whereas prior release's 3.4.0 tag is there. possible to make a 3.5.0 tag while the bug gets sorted out? There might be a chance that it's not carrying the bug.

**Comment by answerquest** [comment]
Query: in this repo, in the Dockerfile, 
If I change `ARG VALHALLA_BUILDER_IMAGE=ghcr.io/valhalla/valhalla:latest` 
to `ARG VALHALLA_BUILDER_IMAGE=ghcr.io/valhalla/valhalla:3.5.0`
and do docker build, then will that take the 3.5.0 release of valhalla? 
any other place any more change to make?

**Comment by chrstnbwnkl** [comment]
that should be good, though from the discussion it seems likely that 3.5.0 already carries the bug, so another easy option for now would be to use 3.4.0, for which there is a tagged version (i know it's relatively old, but it's just until this gets sorted out)

**Comment by chrstnbwnkl** [comment]
I'm closing this issue since it's related to the upstream. In any case, 3.5.0 and 3.5.1 tags are now available, but I'm afraid the change that's causing this issue has been made a while back.

**Comment by answerquest** [comment]
@chrstnbwnkl it seems they identified the bug causing the issue and fixed it : https://github.com/valhalla/valhalla/pull/5005 . 

`ghcr.io/valhalla/valhalla:latest` image has been updated now with this fix; would it be possible for you to trigger an update to  `ghcr.io/nilsnolde/docker-valhalla/valhalla:latest` image as well ?

**Comment by chrstnbwnkl** [comment]
yeah sorry don't have the permissions to do right now. IIRC the weekly build is scheduled for Saturdays, so you can either wait or fork and trigger the build action in your fork.
