### ISSUE TITLE
Adding a gotcha in "Run Valhalla with pre-built tiles"

### ISSUE THREAD

**Issue by tsuz** [gis-ops/docker-valhalla#17]
**What**

I ran the `Run Valhalla with pre-built tiles`[guide](https://github.com/gis-ops/docker-valhalla#run-valhalla-with-pre-built-tiles) but it did not use the tiles (`valhalla_tiles.tar` file) provided. Instead, it built the whole tar file from planet data. I realized I was missing the `.file_hashes.txt` which is the md5 of the file. I added that and the below command was able to use that to start up an instance.

```
docker run -dt -v $PWD/custom_files:/custom_files -p 8002:8002 --name valhalla_1 valhalla
```

**So?**

- Add the instruction about the `.file_hashes.txt` in the readme for future reference.

**Comment by nilsnolde** [comment]
That's also true for `use_tiles_ignore_pbf=True`? I often change the tiles.tar without having the md5 in the hashes. Though that's a good point really.

**Comment by tsuz** [comment]
@nilsnolde 

Interesting. It used to give me an error like `there are no edges around your location` when I ran this without the hash file. Somehow, I cannot reproduce that anymore... I will close this for now. Thanks for your response.
