### ISSUE TITLE
Installation of valhalla on docker on VirtualBox

### ISSUE THREAD

**Issue by courageuse** [gis-ops/docker-valhalla#22]
Hello,
I am in the process of installing valhalla under docker under virtualbox using the ubuntu command lines. to do so, I followed the tutorials below:
1- https://gis-ops.com/valhalla-how-to-run-with-docker-on-ubuntu/
2- https://forums.docker.com/t/command-not-found-when-i-try-to-run-docker-compose/97183/3
3- https://hub.docker.com/r/gisops/valhalla
the question i am asking is that when i type the command: sudo docker ps -a it does not show me the valhalla image.
also when i type the command: curl http: // locallhost: 8002 / route --data '{"locations": [{"lat": 410318818, "lon": 19.461336}, {"lat": 41.321001, "lon": 19.459589}], "costing": "auto", "directions_options": {units ":" miles "}} '| jq'. '
it shows me the following message: curl: (7) failed to connect to localhost port 8002: connection refused.
can someone help me and thank you in advance.

**Comment by nilsnolde** [comment]
This would be a better place, no relation to routing-py..

Did you also look at this repo's README: https://github.com/gis-ops/docker-valhalla? The instructions there work.

**Comment by courageuse** [comment]
thanks Mr nilsnolde for helping me, well I installed a valhalla image under docker under virtualbox, whereas when I type the following command: docker build -t gisops / valhalla

I will get the following message: "docker build" requires exactly 1 argument.
see 'docker build --help'.
Usage: docker build [OPTIONS] PATH | URL | -
Build an image from a Dockerfile 


Thank you in advance.

**Comment by courageuse** [comment]
and when I type the following command line:

sudo docker run -dt -v $PWD/custom_files:/ -p 8002:8002 --name valhalla gisops/valhalla:latest

I will have the following message displayed :

docker: Error response from daemon: Conflict. The container name "/valhalla" is already in use by container "7f92384216410832642e95e263ea1731ea6acd007781cda78a2278144e758f57". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.


for this purpose what to do and where is the problem, can you help me?
and thank you Mr Nilsnolde in advance.

**Comment by nilsnolde** [comment]
> Error response from daemon: Conflict. The container name "/valhalla" is already in use by container "7f92384216410832642e95e263ea1731ea6acd007781cda78a2278144e758f57". You have to remove (or rename) that container to be able to reuse that name.

I can't possibly give you a better response than docker, sorry. Please show the absolute minimum effort to read and understand the messages tools give you (translate if you have to) before posting issues.. alternatively email me on enquiry@gis-ops.com, then I can send you a commercial offer for this type of support and you can pay for my help.
