### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by FlyingEagle** [gis-ops/docker-valhalla#24]
What does this means?

`{"error_code":106,"error":"Try any of:'\/locate' '\/route' '\/height' '\/sources_to_targets' '\/optimized_route' '\/isochrone' '\/trace_route' '\/trace_attributes' '\/transit_available' '\/expansion' '\/centroid' '\/status' ","status_code":404,"status":"Not Found"}`

**Comment by nilsnolde** [comment]
`"status_code":404,"status":"Not Found"` exactly that.

Please consult the valhalla docs, e.g. https://github.com/valhalla/valhalla/blob/master/docs/api/turn-by-turn/api-reference.md
