### ISSUE TITLE
Cannot use base image in Dockerfile - Valhalla docker package

### ISSUE THREAD

**Issue by mickael-bdias** [gis-ops/docker-valhalla#25]
Hi!
Someone could help figure it out why I cannot use the base image in my Dockerfile? 

**Dockerfile (example)**
FROM docker.pkg.github.com/gis-ops/docker-valhalla/valhalla:latest
EXPOSE xxxx

**Terminal**
Step 1/2 : FROM docker.pkg.github.com/gis-ops/docker-valhalla/valhalla:latest
Head https://docker.pkg.github.com/v2/gis-ops/docker-valhalla/valhalla/manifests/latest: no basic auth credentials

Any ideas? 
Do I have to log in? If so, how can I do that?

Thanks!

**Comment by nilsnolde** [comment]
yep, auth missing here you go:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry

**Comment by mickael-bdias** [comment]
Access is even public?
My goal is to use the image and expose another port.
