### ISSUE TITLE
Build with Valhalla 3.1.3.

### ISSUE THREAD

**Issue by mickael-bdias** [gis-ops/docker-valhalla#26]
Hi!

I am trying to build the Docker image as always did, and today with version 3.1.3. I am not able to do my requests.
I am able to make the image.
The container creates all the necessary files, like 'valhalla_tiles.tar'.

This is part of the log:

valhallat_pt | 2021/07/20 22:56:15.924444 [INFO] Finished
valhallat_pt | 2021/07/20 22:56:15.924484 [INFO] Validating, finishing and binning tiles...
valhallat_pt | 2021/07/20 22:56:21.596550 [INFO] Finished
valhallat_pt | 2021/07/20 22:56:21.596614 [INFO] Binning inter-tile edges...
valhallat_pt | 2021/07/20 22:56:22.177698 [INFO] Finished
valhallat_pt | 2021/07/20 22:56:22.177751 [WARN] Possible duplicates at level: 0 = 2
valhallat_pt | 2021/07/20 22:56:22.177761 [WARN] Possible duplicates at level: 1 = 12
valhallat_pt | 2021/07/20 22:56:22.177767 [WARN] Possible duplicates at level: 2 = 0
valhallat_pt | 2021/07/20 22:56:22.187018 [INFO] Cleaning up temporary *.bin files within /valhalla/scripts/valhalla_tiles/
valhallat_pt | tar: Removing leading `/' from member names
valhallat_pt | Successfully built files:  /custom_files/portugal-latest.osm.pbf
valhallat_pt | Hashing files:  /custom_files/portugal-latest.osm.pbf
valhallat_pt | Hashing file: /custom_files/portugal-latest.osm.pbf
valhallat_pt | 2d62dcf6c1e4d4ff6ccdf4e73bb44c5dbc64e8186a7c22e64da55e2b94286d39
valhallat_pt | Found config file. Starting valhalla service!
valhallat_pt | 2021/07/20 22:56:23.545524 [INFO] Tile extract successfully loaded with tile count: 297
valhallat_pt | 2021/07/20 22:56:23.547828 [WARN] (stat):  No such file or directory
valhallat_pt | 2021/07/20 22:56:23.547850 [WARN] Traffic tile extract could not be loaded
valhallat_pt | 2021/07/20 22:56:23.567828 [WARN] /data/valhalla/elevation/ currently has no elevation tiles
valhallat_pt | 2021/07/20 22:56:23.572932 [WARN] /data/valhalla/elevation/ currently has no elevation tiles

The Dockerfile and scripts are the same as this repository.

My docker-compose is the following (ports are masked as xxxx):
version: '3.0'
services:
  valhalla:
    image: valhalla:teste2
    restart: always
    container_name: valhallat_pt
    ports:
      - "xxxx:xxxx"
    volumes:
      - ./custom_files/:/custom_files
    environment:
      # The tile_file must be located in the `custom_files` folder.
      # The tile_file has priority and is used when valid.
      # If the tile_file doesn't exist, the url is used instead.
      # Don't blank out tile_url when you use tile_file and vice versa.
      - tile_urls=https://download.geofabrik.de/europe/portugal-latest.osm.pbf
      # Get correct bounding box from e.g. https://boundingbox.klokantech.com/
      - min_x=-32
      - min_y=29
      - max_x=-5
      - max_y=42
      - server_threads=2
      - use_tiles_ignore_pbf=True
      - force_rebuild=False
      - build_admins=True
      - build_time_zones=True

With my older image, I am able to do my requests.
Something was changed?

Can someone help me?

**Comment by mickael-bdias** [comment]
Hi everybody,
That was a rookie mistake on my part.

Do not forget to change the ports!
custom_files > valhalla.json > httpd > listen

Thanks anyway :)

**Comment by nilsnolde** [comment]
Why you're even changing the port I wonder? It's just the container internal port, not accessible by anyone else but your host. Seems you could simplify that by exposing another port to the host but have 8002 in the container?

**Comment by mickael-bdias** [comment]
Just old habits.
I always change the ports of the image, and the container ports match the image.
It's just a preference.
