### ISSUE TITLE
Is this image production ready ? or is it suitable for handling huge amount of request?

### ISSUE THREAD

**Issue by devShahriar** [gis-ops/docker-valhalla#28]
I am doing a loadtest on valhalla docker image using jmeter . 

In my local machine I am getting average 520ms response time .

Is there any way to improve this performance or any production ready solution ?
Jmeter config
 
![image](https://user-images.githubusercontent.com/56567436/129429425-0f1167e8-5517-4e69-a55a-920f27f4fb68.png)

![image](https://user-images.githubusercontent.com/56567436/129429486-74b8f833-22d5-4056-9929-0d0e046d2ae8.png)

**Comment by TimMcCauley** [comment]
It is production ready but depending on the load you are anticipating Valhalla may struggle serving the requests "fast enough". If you don't require its flexibility, you could have a look at http://project-osrm.org/ which is a magnitude faster.

**Comment by nilsnolde** [comment]
A while ago we published an article about FOSS routing engines, probably helpful for what you want to achieve: https://gis-ops.com/open-source-routing-engines-and-algorithms-an-overview/

**Comment by devShahriar** [comment]
Thanks :D
