### ISSUE TITLE
413 Client Error: Request Entity Too Large

### ISSUE THREAD

**Issue by JackCaster** [gis-ops/docker-valhalla#3]
I am using the service `trace_attributes` but I am getting the error `413 Client Error: Request Entity Too Large` for some large requests. I would like to increase the allowed server body size (see [here](https://craftcms.stackexchange.com/a/2330)) but I do not know where to find the Valhalla server settings. Would you be able to help?

**Comment by nilsnolde** [comment]
No, sorry that's definitely an issue for Valhalla's repo (or their dependency [prime server](https://github.com/kevinkreiser/prime_server), not sure). 

This repo is solely about dockerizing Valhalla, we (intentionally) don't provide any internal server, Valhalla does that by itself and you can put another web server in front of it at your own will.
