### ISSUE TITLE
Error building the config file with the latest image

### ISSUE THREAD

**Issue by mschaffenroth** [gis-ops/docker-valhalla#31]
I am having a problem when creating a config via valhalla_build_config. It seems that disutils needs to be installed in the docker container, see https://stackoverflow.com/questions/3810521/how-to-install-python-distutils

valhalla_latest | = Build the config file =
valhalla_latest | =========================
valhalla_latest | Traceback (most recent call last):
valhalla_latest |   File "/usr/local/bin/valhalla_build_config", line 6, in <module>
valhalla_latest |     from distutils.util import strtobool
valhalla_latest | ModuleNotFoundError: No module named 'distutils.util'

**Comment by nilsnolde** [comment]
hmpf, that's annoying.. I thought there's a full python version installed (and that distutils is an always-shipped std library). at least one of those things is not true. can you try building the image and install distutils in the dockerfile? a PR would be appreciated:)

**Comment by nilsnolde** [comment]
fixed in #32  and pushed to dockerhub.. github packages will be updated saturday
