### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by vinayakkulkarni** [gis-ops/docker-valhalla#34]
hey,

I am able to access the built APIs using cURL but when I try to ingest it in a frontend app, I am getting CORS issue(s).

**Comment by TimMcCauley** [comment]
Are you using a proxy before sending the request to Valhalla? Is your frontend app located on the same domain as where Valhalla is?

**Comment by vinayakkulkarni** [comment]
1. No, I am not using any proxy.
2. Yes, the APIs are on one domain but different sub-domains https://api.<domain>.com/ & the frontend is on another https://frontend.<domain>.com/

**Comment by TimMcCauley** [comment]
Ok, that looks sound. Are you certain your request is valid? Can you copy the request as curl from Chrome or w/e you are using (network tab)?

**Comment by TimMcCauley** [comment]
Closing this now. Please open again if you have any further questions.

**Comment by wkulesza** [comment]
@vinayakkulkarni Could you please let me know how did you fix this? I can also curl (or open in browser) but not through the app - getting 405 Method not allowed...

**Comment by RajaShanmugamJM** [comment]
I wasted entire day trying to find a work around. My findings
1. CORS is not allowed by valhalla
2. OPTIONS method is throwing error

Steps attempted
1. Adding proxy and removing CORS header before proxying
2. Adding proxy to resolve OPTIONS method automatically
3. Making sure both front-end and back-end are in same domain ( in different sub-domains )
4. Tried almost all the CORS extension on chrome.

Proxied using Caddy, (Config file attached below)
Attempt 1:
```
https://valhalla.localhost {
    handle /api {
        rewrite /api /
        reverse_proxy http://localhost:8002
    }

    handle /ui {
        reverse_proxy http://localhost:5173
    }
}
```

Attempt 2:
```
https://valhalla.localhost {
    reverse_proxy http://localhost:8002
}

https://ui.valhalla.localhost {
    reverse_proxy http://localhost:5173
}
```

Attempt 3
```
https://valhalla.localhost {
    handle / {
        reverse_proxy http://localhost:8002 {
            # Remove CORS headers (adjust as needed)
            header_down Access-Control-Allow-Origin
            header_down Access-Control-Allow-Methods
            header_down Access-Control-Allow-Headers
        }
    }

    handle /* {
        method OPTIONS
        respond 200
    }
}
```

If anyone had chance of bypassing this issue, your advise is highly appreciated
