### ISSUE TITLE
Wrong folder mapping

### ISSUE THREAD

**Issue by JackCaster** [gis-ops/docker-valhalla#44]
In the dockerfile template, the mapping between host and docker service is:
https://github.com/gis-ops/docker-valhalla/blob/6fe39a012f32bfc169f27fa6fc06670738c3a283/docker-compose.yml.template#L14
I think some commits ago, this was where Valhalla was saving the processed files. One of the last commits, I believe, reverted this to using
https://github.com/gis-ops/docker-valhalla/blob/6fe39a012f32bfc169f27fa6fc06670738c3a283/scripts/helpers.sh#L4
Thus, I think a docker file should have the following map to work:
```yaml
volumes:
      - ./custom_files/:/custom_files
``` 
otherwise the processed files are not stored on the host. There are several parts in the Readme that should be fixed it too as they indicate to map the folder `valhalla_files`.

**Comment by nilsnolde** [comment]
argh.. yeah that's coming from hurrying things (was a client request)..
