### ISSUE TITLE
consider simplifying Dockerfile

### ISSUE THREAD

**Issue by markstos** [gis-ops/docker-valhalla#50]
Currently this Dockerfile pulls a few files from the `valhalla/valhalla` Docker image, deletes the rest and starts from scratch with a Ubuntu 20.04 base.

But the `valhalla/valhalla` image itself is built on a Ubuntu 20.04 base, and this image is re-installing at least the following packages which are already present in the `valhalla/valhalla` image:

```
curl
jq
libluajit-5.1-2 
libsqlite3-mod-spatialite 
parallel 
spatialite-bin 
unzip 
```
It would seem to simplify the system overall if this Docker image was simply based directly on the `valhalla/valhalla` image, and then only added the additional dependencies it needs.

**Comment by nilsnolde** [comment]
that's actually very much on purpose. the valhalla image is _huge_, it has the (gzipped but still) entire debug symbol stuff. honestly I'm not sure anymore if deleting stuff from a base image really drives down the final image size much with docker's layering scheme, but also I wouldn't prefer that. I rather pull in from the valhalla/valhalla base image what I need in a multi-stage process. much cleaner IMHO.

I agree that curl can go though, true.
