### ISSUE TITLE
How to increase exclude_polygons param?

### ISSUE THREAD

**Issue by eugenesotnikov** [gis-ops/docker-valhalla#52]
Hello
   We got error "Exceeded maximum circumference for exclude_polygons". I tried to find this param in repos. Didn't find.
But found only in valhalla/valhalla  valhalla_build_config
'max_exclude_polygons_length': 10000

Do you plan to add this param to your project? We need to increase it very much.

**Comment by TimMcCauley** [comment]
You should be able to simply manipulate this parameter in your config.json and restart the container afterwards. https://github.com/valhalla/valhalla/blob/master/bench/meili/config.json#L82

**Comment by eugenesotnikov** [comment]
Do you mean file valhalla.json in custom_files?

**Comment by TimMcCauley** [comment]
Correct

**Comment by TimMcCauley** [comment]
> Do you mean file valhalla.json in custom_files?

correct !

**Comment by eugenesotnikov** [comment]
Wow! That's greate! It's work. So easy. Thanks!

**Comment by TimMcCauley** [comment]
Very welcome 🙏
