### ISSUE TITLE
docker-compose: sudo: /valhalla/scripts/configure_valhalla.sh: command not found

### ISSUE THREAD

**Issue by mickael-bdias** [gis-ops/docker-valhalla#55]
Hello all,

I used the Dockerfile to build the image (just changed the ports).
And then:
- Copied the scripts
- Give permission to those scripts sh

When I tried to use docker-compose:

Creating valhalla ... done
Attaching to valhalla
valhalla    |
valhalla    | INFO: Running container with user valhalla UID 59999 and GID 59999.
valhalla    |
valhalla    | sudo: /valhalla/scripts/configure_valhalla.sh: command not found

Thanks.

**Comment by nilsnolde** [comment]
hm not sure.. without exact commands and the docker-compose it's also impossible to tell. does the pre-built image from dockerhub/github work for you?

**Comment by mickael-bdias** [comment]
1. I used the Dockerfile and scripts of this  repo
2. Build the image (just changed the ports to 6001 and named to valhalla:0.0.6)
3. docker-compose up --build

docker-compose.yml
version: '3.0'
services:
  valhalla:
    image: valhalla:0.0.6
    restart: always
    container_name: valhalla
    ports:
      - "6001:6001"
    volumes:
      - ./custom_files/:/custom_files
    environment:
      # Auto-download PBFs from Geofabrik
      # - tile_urls=https://download.geofabrik.de/europe/portugal-latest.osm.pbf https://download.geofabrik.de/europe/spain-latest.osm.pbf
      - server_threads=2  # determines how many threads will be used to run the valhalla server
      - use_tiles_ignore_pbf=True  # load existing valhalla_tiles.tar directly
      - build_elevation=False  # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
      - build_admins=False  # build admins db with "True" or "Force"
      - build_time_zones=False  # build timezone db with "True" or "Force"
      - build_tar=True  # build an indexed tar file from the tile_dir for faster graph loading times
      - force_rebuild=False  # forces a rebuild of the routing tiles with "True"
      # - path_extension=graphs  # this path will be internally appended to /custom_files; no leading or trailing path separator!
    # adapt to the expected build time
    # healthcheck: 
    #   test: curl --fail -s http://localhost:8002/status || exit 1
    #   interval: 1s
    #   retries: 10
    #   start_period: 2s
    #   timeout: 1s

PS: I´ve a directory named 'valhalla' inside this dir:
1. dir custom_files
2. dir scripts
3. Dockerfile
4. docker-compose.yml

Thank you!

**Comment by mickael-bdias** [comment]
This is the Dockerfile:

**Comment by nilsnolde** [comment]
still don't know actually.. the script is copied in our dockerfile: https://github.com/gis-ops/docker-valhalla/blob/058ba03e13bee73f95ac5d28ac109fac15d50e32/Dockerfile#L54. so somehow you must've deviated from that. our image builds fine, just 2 days ago on dockerhub. good luck still!
