### ISSUE TITLE
memory not being released

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/docker-valhalla#63]
@nmalasevic just encountered a serious flaw in our image, not being present in the upstream valhalla image:
https://github.com/valhalla/valhalla/issues/3556#issuecomment-1058244884

also sounds pretty terrible to debug.. open for suggestions!:)

**Comment by nmalasevic** [comment]
Sounds like every request is behaving like an instance of it's own, so cached memory is not being reused in case of subsequent requests (same request).

**Comment by nilsnolde** [comment]
the way the tile cache works it _shouldn't_ be possible (I think), also I don't see how that should be caused by the way we run things in the container. I guess it's some weird interaction of the docker entrypoint script and docker.. maybe the `exec "$@"` line, no idea.. will poke around a bit soon-ish.
