### ISSUE TITLE
Hashes aren't being generated for country PBF files

### ISSUE THREAD

**Issue by mrantivirus** [gis-ops/docker-valhalla#68]
### Server
Azure VM: Standard_F2s_v2

- 4GB RAM
- 2 vCPU
- 200GB SSD

I'm not sure what the exact issue is or how to get information on the crash, but I consistently have issues getting the server running. I'm using the latest Japan, Malaysia, Korea & Thailand pbf files from geofabrik with the latest version of `gis-ops/valhalla` image with the `build_admins` variable set to true.

From the logs I attached below, after running the `HierarchyBuilder`, there seems to be a crash for some reason. The container restarts and tries building the initial graph again. 

I didn't see the logs previously since I put it on fire and forget a few days ago, but it "finished" processing the files (or failed but somehow started the valhalla service). So when I tried making API calls with coordinates inside of those countries, it returned `“error”: “No suitable edges near location”`. So this made me assume that the country files weren't processed. If I restarted the container with `build_admins` not set, then I can see that it says it couldn't find hashes for the pbf files. So I wiped the directory and restarted the container today and watched the server. That is how I was able to copy and paste the logs below.

I tried with the planet file, but I need a much larger storage volume as 200GB wasn't enough for the planet file + the generated graph, so I deleted that and put the country files back to be processed. 

If there a way I can generate an error log or dump that you/I can review to figure out what could be the issue. Nothing seems clear just looking at the logs.

### Logs
<details>
<summary>Container logs</summary>

INFO: Running container with user valhalla UID 59999 and GID 59999.

WARNING: Hash not found for: /custom_files/japan-latest.osm.pbf!
WARNING: Hash not found for: /custom_files/malaysia-singapore-brunei-latest.osm.pbf!
WARNING: Hash not found for: /custom_files/south-korea-latest.osm.pbf!
WARNING: Hash not found for: /custom_files/thailand-latest.osm.pbf!
WARNING: No admin db found, starting a new build

=====================
= Building admin db =
=====================

2022/05/26 23:54:14.655898 [INFO] Parsing files: /custom_files/japan-latest.osm.pbf, /custom_files/malaysia-singapore-brunei-latest.osm.pbf, /custom_files/south-korea-latest.osm.pbf, /custom_files/thailand-latest.osm.pbf
2022/05/26 23:54:14.656012 [INFO] Parsing relations...
2022/05/26 23:55:25.356968 [INFO] Finished with 221 admin polygons comprised of 17160 ways
2022/05/26 23:55:25.356998 [INFO] Parsing ways...
2022/05/26 23:56:37.523384 [INFO] Finished with 4870 ways comprised of 580851 nodes
2022/05/26 23:56:37.523422 [INFO] Parsing nodes...
2022/05/26 23:58:14.294728 [INFO] Processed 500000 nodes on ways
2022/05/26 23:58:25.255240 [INFO] Finished with 575780 nodes
2022/05/26 23:58:25.404963 [INFO] Created admin access table.
2022/05/26 23:58:25.528859 [INFO] Created admin table.
2022/05/26 23:58:37.004080 [INFO] Inserted 174 admin areas
2022/05/26 23:58:37.201168 [INFO] Created spatial index
2022/05/26 23:58:37.222073 [INFO] Created Level index
2022/05/26 23:58:37.242988 [INFO] Created Drive On Right index
2022/05/26 23:58:37.259154 [INFO] Created allow intersection names index
2022/05/26 23:58:41.249057 [INFO] Done updating drive on right column.
2022/05/26 23:58:41.651497 [INFO] Done updating allow intersection names column.
2022/05/26 23:58:49.715241 [INFO] Done updating Parent admin
2022/05/26 23:58:49.715800 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Turkey
2022/05/26 23:58:49.715921 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Russia
2022/05/26 23:58:49.716032 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Romania
2022/05/26 23:58:49.716146 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for United States
2022/05/26 23:58:49.716253 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Poland
2022/05/26 23:58:49.716376 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Philippines
2022/05/26 23:58:49.716494 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Slovakia
2022/05/26 23:58:49.716602 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Oman
2022/05/26 23:58:49.716736 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Sweden
2022/05/26 23:58:49.716849 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Norway
2022/05/26 23:58:49.716965 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Netherlands
2022/05/26 23:58:49.717065 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for United Kingdom
2022/05/26 23:58:49.717179 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Italy
2022/05/26 23:58:49.717295 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Ireland
2022/05/26 23:58:49.717419 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Iceland
2022/05/26 23:58:49.717536 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Hungary
2022/05/26 23:58:49.717667 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Greece
2022/05/26 23:58:49.717789 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Switzerland
2022/05/26 23:58:49.717909 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Finland
2022/05/26 23:58:49.718021 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for France
2022/05/26 23:58:49.718136 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Spain
2022/05/26 23:58:49.718251 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for China
2022/05/26 23:58:49.718365 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Belgium
2022/05/26 23:58:49.718479 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Brazil
2022/05/26 23:58:49.718594 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Belarus
2022/05/26 23:58:49.718712 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Denmark
2022/05/26 23:58:49.718834 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Austria
2022/05/26 23:58:49.718952 [ERROR] sqlite3_step() error: NOT NULL constraint failed: admin_access.admin_id.  Ignore if not using a planet extract or check if there was a name change for Australia
2022/05/26 23:58:49.719830 [INFO] Finished.
INFO: Running build tiles with: /custom_files/valhalla.json /custom_files/japan-latest.osm.pbf /custom_files/malaysia-singapore-brunei-latest.osm.pbf /custom_files/south-korea-latest.osm.pbf /custom_files/thailand-latest.osm.pbf

============================
= Build the initial graph. =
============================
2022/05/26 23:58:49.830698 [INFO] Start stage = initialize End stage = build
2022/05/26 23:58:49.831925 [WARN] Non-empty /custom_files/valhalla_tiles/0 will be purged of tiles
2022/05/26 23:58:49.837460 [WARN] Non-empty /custom_files/valhalla_tiles/1 will be purged of tiles
2022/05/26 23:58:49.849382 [WARN] Non-empty /custom_files/valhalla_tiles/2 will be purged of tiles
2022/05/26 23:58:49.914840 [INFO] Parsing files for ways: /custom_files/japan-latest.osm.pbf, /custom_files/malaysia-singapore-brunei-latest.osm.pbf, /custom_files/south-korea-latest.osm.pbf, /custom_files/thailand-latest.osm.pbf
2022/05/26 23:58:50.122646 [INFO] Parsing ways...
2022/05/27 00:02:30.490156 [WARN] Error during parsing of `layer` tag on the way 549551378: stoi
2022/05/27 00:02:30.491465 [WARN] Error during parsing of `layer` tag on the way 549551379: stoi
2022/05/27 00:02:49.200212 [WARN] Error during parsing of `layer` tag on the way 635507989: stoi
2022/05/27 00:02:55.316616 [WARN] Error during parsing of `layer` tag on the way 676718745: stoi
2022/05/27 00:03:19.814772 [WARN] Error during parsing of `layer` tag on the way 817987024: stoi
2022/05/27 00:03:19.814899 [WARN] Error during parsing of `layer` tag on the way 817987025: stoi
2022/05/27 00:03:19.815435 [WARN] Error during parsing of `layer` tag on the way 817987056: stoi
2022/05/27 00:03:49.170437 [WARN] Error during parsing of `layer` tag on the way 1035569516: stoi
2022/05/27 00:03:51.071034 [WARN] Error during parsing of `layer` tag on the way 1047430460: stoi
2022/05/27 00:09:48.035336 [INFO] Added 7966 culdesac roundabouts from 20870 candidates.
2022/05/27 00:09:48.035699 [INFO] Finished with 14110835 routable ways containing 127187689 nodes
2022/05/27 00:09:48.130120 [INFO] Sorting osm access tags by way id...
2022/05/27 00:09:53.342640 [INFO] Sorting pronunciation indexes by way id...
2022/05/27 00:09:53.343253 [INFO] Finished
2022/05/27 00:09:53.387766 [INFO] Write OSMData to temp files
2022/05/27 00:09:53.506750 [INFO] Done
2022/05/27 00:09:53.509910 [INFO] Parsing files for relations: /custom_files/japan-latest.osm.pbf, /custom_files/malaysia-singapore-brunei-latest.osm.pbf, /custom_files/south-korea-latest.osm.pbf, /custom_files/thailand-latest.osm.pbf
2022/05/27 00:09:53.510115 [INFO] Parsing relations...
2022/05/27 00:11:52.456104 [INFO] Finished with 173482 simple restrictions
2022/05/27 00:11:52.456136 [INFO] Finished with 0 lane connections
2022/05/27 00:11:52.472272 [INFO] Sorting complex restrictions by from id...
2022/05/27 00:11:52.480048 [INFO] Sorting complex restrictions by to id...
2022/05/27 00:11:52.486743 [INFO] Finished
2022/05/27 00:11:52.487223 [INFO] Write OSMData to temp files
2022/05/27 00:11:52.827306 [INFO] Done
2022/05/27 00:11:52.828681 [INFO] Parsing files for nodes: /custom_files/japan-latest.osm.pbf, /custom_files/malaysia-singapore-brunei-latest.osm.pbf, /custom_files/south-korea-latest.osm.pbf, /custom_files/thailand-latest.osm.pbf
2022/05/27 00:11:52.828760 [INFO] Sorting osm way node references by node id...
2022/05/27 00:24:57.088403 [INFO] Parsing nodes...
2022/05/27 00:46:24.995948 [INFO] Finished with 106712941 nodes contained in routable ways
2022/05/27 00:46:24.996205 [INFO] Sorting osm way node references by way index and node shape index...
2022/05/27 00:58:21.275737 [INFO] Finished: max_osm_id 9764915243
2022/05/27 00:58:21.276149 [INFO] Number of nodes with refs (exits) = 6788
2022/05/27 00:58:21.276156 [INFO] Number of nodes with exit_to = 243
2022/05/27 00:58:21.276161 [INFO] Number of nodes with names = 84917
2022/05/27 00:58:21.276164 [INFO] Number of way refs = 38
2022/05/27 00:58:21.276167 [INFO] Number of reverse way refs = 0
2022/05/27 00:58:21.276171 [INFO] Unique Node Strings (names, refs, etc.) = 56866
2022/05/27 00:58:21.276174 [INFO] Unique Strings (names, refs, etc.) = 426137
2022/05/27 00:58:21.279082 [INFO] Write OSMData to temp files
2022/05/27 00:58:22.080134 [INFO] Done
2022/05/27 00:58:22.081158 [INFO] Creating graph edges from ways...
2022/05/27 01:01:24.045604 [INFO] Finished with 26923930 graph edges
2022/05/27 01:01:24.139318 [INFO] Sorting graph...
2022/05/27 01:06:13.534402 [INFO] Nodes processed. Sorting begin and end nodes by edge.
2022/05/27 01:06:29.802593 [INFO] Sorting begin and end nodes done. Populating edges...
2022/05/27 01:06:42.221664 [INFO] Finished with 20536404 graph nodes
2022/05/27 01:06:42.311656 [INFO] Writing tile manifest to /custom_files/valhalla_tiles/tile_manifest.json
2022/05/27 01:06:42.312502 [INFO] Reclassifying_V2 link graph edges...
2022/05/27 01:07:39.215050 [INFO] Class: 0 exit count = 9154
2022/05/27 01:07:39.215764 [INFO] Class: 1 exit count = 28298
2022/05/27 01:07:39.215770 [INFO] Class: 2 exit count = 26595
2022/05/27 01:07:39.215774 [INFO] Class: 3 exit count = 24624
2022/05/27 01:07:39.215777 [INFO] Class: 4 exit count = 20059
2022/05/27 01:07:39.215780 [INFO] Class: 5 exit count = 8974
2022/05/27 01:07:39.215783 [INFO] Class: 6 exit count = 13068
2022/05/27 01:07:39.215786 [INFO] Class: 7 exit count = 0
2022/05/27 01:17:26.109902 [INFO] Finished with 123161 reclassified.  Turn channel count = 64209
2022/05/27 01:17:26.208932 [INFO] Reclassifying ferry connection graph edges...
2022/05/27 01:19:59.566102 [INFO] Finished ReclassifyFerryEdges: ferry_endpoint_count = 687, 13336 edges reclassified.
2022/05/27 01:19:59.703775 [INFO] Building 2686 tiles with 2 threads...
2022/05/27 01:19:59.721485 [WARN] Time zone db /custom_files/timezone_data/timezones.sqlite not found.  Not saving time zone information.
2022/05/27 01:19:59.721485 [WARN] Time zone db /custom_files/timezone_data/timezones.sqlite not found.  Not saving time zone information.
2022/05/27 01:53:47.523282 [WARN] Restrictions mask exceeds allowable limit on wayid: 166728237
2022/05/27 01:53:47.524153 [WARN] Restrictions mask exceeds allowable limit: 509
2022/05/27 02:13:32.697005 [INFO] Finished
2022/05/27 02:13:32.713950 [INFO] Node Count = 20536404
2022/05/27 02:13:32.714203 [INFO] Directed Edge Count = 53847860
2022/05/27 02:13:32.714361 [INFO] EdgeInfo Count = 27076910

===============================
= Enhancing the initial graph =
===============================
2022/05/27 02:13:33.056488 [INFO] Start stage = enhance End stage = cleanup
2022/05/27 02:13:33.057423 [INFO] Read OSMData unique_names from temp file
2022/05/27 02:13:33.381942 [INFO] Done
2022/05/27 02:13:33.381976 [INFO] Enhancing local graph...
2022/05/27 02:13:33.797310 [INFO] Disabled default speeds assignment from config
2022/05/27 02:13:33.797427 [INFO] Disabled default speeds assignment from config
2022/05/27 02:22:23.876192 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 02:28:25.393072 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 02:28:25.393395 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 02:28:25.393447 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 02:28:25.393506 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 02:28:25.393686 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 02:28:25.393785 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 02:28:25.393815 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 02:46:16.219071 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:08:19.192315 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:08:19.194020 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2022/05/27 03:08:19.206192 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
2022/05/27 03:08:19.206297 [WARN] Local index 11 exceeds max value of 7, returning heading of 0
2022/05/27 03:08:19.206687 [WARN] Local index 12 exceeds max value of 7, returning heading of 0
2022/05/27 03:08:19.206761 [WARN] Local index 13 exceeds max value of 7, returning heading of 0
2022/05/27 03:08:19.206976 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:08:19.207221 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2022/05/27 03:08:19.208651 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
2022/05/27 03:08:19.208718 [WARN] Local index 11 exceeds max value of 7, returning heading of 0
2022/05/27 03:08:19.208760 [WARN] Local index 12 exceeds max value of 7, returning heading of 0
2022/05/27 03:08:19.208788 [WARN] Local index 13 exceeds max value of 7, returning heading of 0
2022/05/27 03:14:19.087781 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:14:19.087824 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2022/05/27 03:14:19.087848 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2022/05/27 03:14:19.087853 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:27:32.348973 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:40:27.175108 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:40:27.176490 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:40:27.176525 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:40:27.179363 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:40:27.179803 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:40:27.180207 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:40:27.180264 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:40:27.180441 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:44:02.102543 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:44:02.102974 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2022/05/27 03:48:10.483279 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:56:42.209355 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:56:42.209695 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:56:42.209819 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:56:42.210135 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:56:42.210169 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:56:42.210218 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:56:42.210264 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:56:42.210293 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:56:42.210345 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 03:56:42.210380 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2022/05/27 03:56:42.210400 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.819675 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820126 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820134 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820137 [WARN] Local index 11 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820140 [WARN] Local index 12 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820144 [WARN] Local index 13 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820147 [WARN] Local index 14 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820150 [WARN] Local index 15 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820154 [WARN] Local index 16 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820407 [WARN] Local index 17 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820426 [WARN] Local index 18 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820430 [WARN] Local index 19 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820433 [WARN] Local index 20 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820437 [WARN] Local index 21 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.820478 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827144 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827169 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827174 [WARN] Local index 11 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827177 [WARN] Local index 12 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827181 [WARN] Local index 13 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827184 [WARN] Local index 14 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827205 [WARN] Local index 15 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827211 [WARN] Local index 16 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827215 [WARN] Local index 17 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827219 [WARN] Local index 18 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827224 [WARN] Local index 19 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827229 [WARN] Local index 20 exceeds max value of 7, returning heading of 0
2022/05/27 04:01:33.827233 [WARN] Local index 21 exceeds max value of 7, returning heading of 0
2022/05/27 04:08:38.480668 [INFO] Finished with max_density 39.234520
2022/05/27 04:08:38.480703 [INFO] internal intersection = 334136
2022/05/27 04:08:38.482272 [INFO] GraphFilter - nothing to filter. Skipping...
2022/05/27 04:08:38.482900 [INFO] Transit directory not found. Transit will not be added.
2022/05/27 04:08:38.483305 [INFO] HierarchyBuilder
2022/05/27 04:17:51.290546 [INFO] Done HierarchyBuilder
2022/05/27 04:17:51.294534 [INFO] Creating shortcuts on level 1
2022/05/27 04:18:09.655698 [WARN] Exceeding max shortcut edges from a node at LL = 35.543681,139.603932
2022/05/27 04:18:13.414916 [WARN] Exceeding max shortcut edges from a node at LL = 37.561143,127.035442
2022/05/27 04:18:16.971222 [INFO] Finished with 841232 shortcuts
2022/05/27 04:18:16.971256 [INFO] Creating shortcuts on level 0
2022/05/27 04:18:28.819001 [WARN] Exceeding max shortcut edges from a node at LL = 37.752881,140.463945
2022/05/27 04:18:30.289304 [INFO] Finished with 267354 shortcuts
2022/05/27 04:18:30.289445 [WARN] Elevation storage directory does not exist
2022/05/27 04:18:30.658774 [INFO] Adding Restrictions at level 2
/valhalla/scripts/configure_valhalla.sh: line 172:    68 Killed                  valhalla_build_tiles -c ${CONFIG_FILE} -s enhance ${files}
user@router:~$ df -lh
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        30G  4.3G   26G  15% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           786M  1.2M  784M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  5.3M  100M   5% /boot/efi
/dev/sdc1       196G   83G  103G  45% /valhalla_files
/dev/sdb1        16G   45M   16G   1% /mnt
tmpfs           393M  4.0K  393M   1% /run/user/1000
<details>

**Comment by nilsnolde** [comment]
Look at the very end, it says “killed”: you have too little RAM, it’s OOM. I’d try at least doubling that and try again.
