### ISSUE TITLE
 Transit directory not found. Transit will not be added.

### ISSUE THREAD

**Issue by MatthewLehane** [gis-ops/docker-valhalla#73]
Hello,

When I was setting up the docker contained, this line popped up in PowerShell and got me curious " Transit directory not found. Transit will not be added."  However, I am having trouble finding information on the "transit directory". What is the process to add this to the setup of the docker container?

Thanks!

**Comment by nilsnolde** [comment]
Complicated topic 😄 We’re in the process of supporting GTFS directly via a GSoC project. Best to follow that: https://github.com/valhalla/valhalla/commits/master
