### ISSUE TITLE
[Request]Host docker image on ECR public

### ISSUE THREAD

**Issue by khavishbhundoo** [gis-ops/docker-valhalla#74]
Hi, 

It will be great to have the docker-valhalla hosted on  https://gallery.ecr.aws/ . AWS ECR has support for pull cache repo and if it is hosted on https://gallery.ecr.aws/ then we could access the image private rather than going on the public internet.

**Comment by nilsnolde** [comment]
I don’t have a problem with that, but would expect others to take action. We don’t use AWS and likely never will. Is it possible for you to register it there?

**Comment by khavishbhundoo** [comment]
It would be better if you register it there so that you have full control over the repo and can push docker-valhalla images with a github action . Its free to upload up to 50gb of images to AWS public ecr repo and its users that pull the images who pay. 

https://aws.amazon.com/blogs/aws/amazon-ecr-public-a-new-public-container-registry/
https://aws.amazon.com/ecr/pricing/

> As a new Amazon ECR customer, you get 500 MB per month of storage for your private repositories for one year as part of the [AWS Free Tier.](https://aws.amazon.com/free/)

> Both new and existing customers get 50 GB per month of always-free storage for their public repositories. You can anonymously (without using an AWS account) transfer 500 GB of data to the Internet from a public repository each month for free. If you sign up for an AWS account, or authenticate to Amazon ECR with an existing AWS account, you can transfer 5 TB of data to the Internet from a public repository each month for free. You also get unlimited bandwidth at no cost when transferring data from a public repository to AWS compute resources in any AWS Region.

**Comment by nilsnolde** [comment]
Ok, if it’s that easy, I’d accept a pull request to add AWS as another registry to our GitHub Action publishing workflows.

**Comment by nilsnolde** [comment]
feel free to open again if necessary
