### ISSUE TITLE
wish: option to skip the "enhance" build phase

### ISSUE THREAD

**Issue by markstos** [gis-ops/docker-valhalla#75]
The "enhance" build phase appears non-essential, and has been known to  trigger "hangs". For example, a "hang" in this phase is documented here. There was no fix to the Valhalla project as a result. Instead, the issue went away after the OSM data was updated. 

I'm also experiencing a hang at this stage currently, and it's not clear I actually need whatever it is the `enhance` phase does to update the graph data.

It could be I'm mistaken and the `enhance` phase is essential, but so far I'm having trouble finding documentation about that. 

https://github.com/valhalla/valhalla/issues/3499

**Comment by nilsnolde** [comment]
There's hardly any documentation on it, true, you'd need to sift through the code with quite some initial understanding how Valhalla works. Ref https://github.com/valhalla/valhalla/discussions/3744#discussioncomment-3632560.

It's easy enough for you to patch our logic: https://github.com/gis-ops/docker-valhalla/blob/4a7daf2dd934c8cf32b31fa755bd4a0a20c488ad/scripts/configure_valhalla.sh#L139-L172

I wouldn't like this option upstream though, it's too unpredictable for users IMO, and we'd never use it ourselves.

**Comment by markstos** [comment]
Thanks for the feedback.
