### ISSUE TITLE
Crash on the valhalla_build_tiles command

### ISSUE THREAD

**Issue by zcs0228** [gis-ops/docker-valhalla#84]
![image](https://user-images.githubusercontent.com/10859397/215934658-f332a137-b2bd-4410-a9af-270869f186dd.png)

**Comment by nilsnolde** [comment]
And? If you look at this without any context, do you think you'd understand what happend?

Please, no (incomplete) screenshots of text and no asking for unpaid help with zero explanation what was done (command, full log, OSM data etc..).

**Comment by nilsnolde** [comment]
Aaaand blocked..
